version: '3'
services:
  pyspark:
    image: jupyter/pyspark-notebook:latest
    network_mode: "host"
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=1000
      - NB_GID=1000
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
    user: root
    command: start-notebook.sh --NotebookApp.allow_root=true
    restart: always